### ISSUE TITLE
June 2nd Review Checklist

### ISSUE THREAD

**Issue by bmarika** [MasterFacilityList/masterfacilitylist.github.io#6]
@owagaantony @jason-wanjohi 
-  [ ] Redo the video with a good mic and use [Camstasia](https://www.techsmith.com/camtasia.html) 
- [ ] Style the training site home page. (Hand Craft the index.html)
- [ ] Add manuals for the admin site
